version: "3.8"

services:
  web:
    build: .
    container_name: gameboard_api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3

  redis:
    image: "redis:alpine"
    container_name: gameboard_redis
    restart: always

  celery_worker:
    build: .
    container_name: gameboard_celery_worker
    command: celery -A gameboard worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  celery_beat:
    build: .
    container_name: gameboard_celery_beat
    command: celery -A gameboard beat --loglevel=info
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
